version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: django
    versions:
    - ">= 3.a, < 4"
  - dependency-name: astroid
    versions:
    - 2.5.3
    - 2.5.4
    - 2.5.5
