language: python

dist: xenial

sudo: false

cache:
  pip: true
  directories:
  - $HOME/.m2
  - $HOME/.npm

services:
  - mysql

python:
  - "3.5"
  - "3.6"
  - "3.7"
  
install:
  - pip install -r ./requirements.txt
  - pip install coveralls
  
matrix:
  fast_finish: true
  
script: 
  - coverage run --source='.' manage.py test
  - coverage report
  
after_success:
  - coveralls
