language: python

dist: xenial

sudo: false

cache:
  pip: true
  directories:
  - $HOME/.m2
  - $HOME/.npm

services:
  - mysql

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest

python:
  - "3.5"
  - "3.6"
  - "3.7"
  
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - tar xf geckodriver-v0.24.0-linux64.tar.gz

install:
  - pip install -r ./requirements.txt
  - pip install coveralls
  
matrix:
  fast_finish: true
  
script:
  - export PYTHONWARNINGS=all
  - python manage.py check
  - python manage.py makemigrations --dry-run --check
  - PATH=.:$PATH coverage run --source='.' manage.py test
  - coverage report
  
after_success:
  - coveralls
